### PR TITLE
Refactor/update token offset finder

### PR DESCRIPTION
**Pull request by Will-Smith11**
Allows us to be able to delete the config file with the slot offset and just generically fetch them

### CODE REVIEW

**Comment by Philogy** [comment]
@Will-Smith11 could you give a TL;DR on methodology?

**Comment by Will-Smith11** [comment]
> @Will-Smith11 could you give a TL;DR on methodology?

When we need to check a balance / approval in verification, what we do is just probe for the slot offsets of these mappings (assumtion is soldity storage hashing and no shared mapping). so it goes and see if it has been calcuated. if not it probes the first 100 slots offsets to find the approval / balance mappings. this allows us to just do a single db call and avoid having to run the evm on every transaction

**Comment by Philogy** [comment]
> When we need to check a balance / approval in verification, what we do is just probe for the slot offsets of these mappings (assumtion is soldity storage hashing and no shared mapping). so it goes and see if it has been calcuated. if not it probes the first 100 slots offsets to find the approval / balance mappings. this allows us to just do a single db call and avoid having to run the evm on every transaction

Ah so you optimistically just probe the first 100 slots? Will break with some tokens but should be fine. Maybe add a checklist to the docs with this point in terms of checking that a certain ERC20 is safe to add to Angstrom

**Comment by Will-Smith11** [comment]
> checklist to the docs with this point in terms of checking that a certain ERC20 is safe
yeah this was the plan

**Pull request merged**
